import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>website maria sofia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenidos a mi sitio web  <a href="https://github.com/masoviga">masoviga!</a>
        </h1>
        <h2>
          Buenas Mi nombre es Sofia esta es mi segunda pagina web y me gusta la comida italiana, porque lees esto .-.?
        </h2>
        <div>
          <Image src="/wiii.jpg" alt="imagen wii" width={300} height={300} />
          <Image src="/deformito.jpg" alt="imagen wii" width={300} height={300} />
          <Image src="/holaquemas.webp" alt="imagen wii" width={300} height={300} />
        </div>
        <h3>
          BUENO CHAU SI TE GUSTO ENTONCES QUE BIEN SI NO AH BUENO :V
        </h3>
      </main>

      <footer className={styles.footer}>
        <a 
          target="_blank"
          rel="noopener noreferrer"
        >
          creado por Maria Sofia 
          
        </a>
      </footer>
    </div>
  )
}
